io:
  datadir: /content/drive/MyDrive/smartMTO-Xavier/Train_lcnn_dpid/Twoclass
  logdir: /content/drive/MyDrive/smartMTO-Xavier/Train_lcnn_dpid/logs/twoclass
  num_workers: 2
  resume_from: /content/drive/MyDrive/smartMTO-Xavier/Train_lcnn_dpid/logs/twoclass/230926-142433-98d3f67-baseline
  tensorboard_port: 0
  validation_interval: 24000
model:
  backbone: stacked_hourglass
  batch_size: 4
  batch_size_eval: 2
  depth: 4
  dim_fc: 1024
  dim_loi: 128
  eval_junc_thres: 0.008
  head_size:
  - - 4
  - - 1
  - - 4
  image:
    mean:
    - 247.55
    stddev:
    - 41.36
  loss_weight:
    jmap: 8.0
    joff: 0.25
    lmap: 0.5
    lneg: 1
    lpos: 1
  n_dyn_junc: 300
  n_dyn_negl: 80
  n_dyn_othr: 600
  n_dyn_posl: 300
  n_out_junc: 250
  n_out_line: 2500
  n_pts0: 32
  n_pts1: 8
  n_stc_negl: 40
  n_stc_posl: 300
  num_blocks: 1
  num_stacks: 2
  use_conv: 0
  use_cood: 0
  use_slop: 0
optim:
  amsgrad: true
  lr: 0.0004
  lr_decay_epoch: 10
  max_epoch: 24
  name: Adam
  weight_decay: 0.0001
