io:
  logdir: /content/drive/MyDrive/smartMTO-Xavier/Train_lcnn_dpid/logs/dpid_complete/
  datadir: /content/drive/MyDrive/smartMTO-Xavier/Train_lcnn_dpid/complete
  resume_from: #/content/drive/MyDrive/Xavier/logs/dpid_complete/231108-103904-b992149-baseline
  num_workers: 2
  tensorboard_port: 0
  validation_interval: 24000

model:
  image:
      mean: [247.55]
      stddev: [41.36]

  batch_size: 2
  batch_size_eval: 1

  # backbone multi-task parameters
  # jmap, lmap, joff
  head_size: [[68], [6], [68]]
  loss_weight:
    jmap: 0.01
    lmap: 0.5
    joff: 0.25
    lpos0: 10
    lpos1: 10
    lpos2: 10
    lneg: 10
    jtype: 0.1

  # backbone parameters
  backbone: stacked_hourglass
  depth: 5
  num_stacks: 2
  num_blocks: 2

  # sampler parameters
  ## static sampler
  n_stc_posl0: 100
  n_stc_posl1: 200
  n_stc_posl2: 200
  n_stc_negl: 200

  ## dynamic sampler
  n_dyn_junc: 400
  n_dyn_posl0: 400
  n_dyn_posl1: 400
  n_dyn_posl2: 400
  n_dyn_negl: 400
  n_dyn_othr: 400

  # LOIPool layer parameters
  n_pts0: 32
  n_pts1: 8

  # line verification network parameters
  dim_loi: 256
  dim_fc: 1024

  # maximum junction and line outputs
  n_out_junc: 600
  n_out_line: 2000

  # additional ablation study parameters
  use_cood: 0
  use_slop: 0
  use_conv: 0
  use_half: 0
  use_jtyp: 0

  CE_lines: 0
  focal_lines: 1
  CE_keypoints: 0
  focal_keypoints: 1

  # evaluation
  use_wandb: 0

  # junction threashold for evaluation (See #5)
  eval_junc_thres: 0.01

optim:
  name: Adam
  lr: 4.0e-4
  amsgrad: True
  weight_decay: 0
  max_epoch: 24
  lr_decay_epoch: 0
