io:
  logdir: /content/drive/MyDrive/Xavier/logs/overfit_smaller
  datadir: /content/drive/MyDrive/Xavier/Datasets/overfit_smaller
  resume_from:  /content/drive/MyDrive/Xavier/logs/overfit_smaller/231030-215807-693cad6-baseline
  num_workers: 2
  tensorboard_port: 0
  validation_interval: 24000

model:
  image:
      mean: [247.55]
      stddev: [41.36]

  batch_size: 2
  batch_size_eval: 2

  # backbone multi-task parameters
  # jmap, lmap, joff
  head_size: [[68], [6], [68]]
  loss_weight:
    jmap: 0.5
    lmap: 0.5
    joff: 0.25
    lpos0: 1
    lpos1: 1
    lpos2: 1
    lneg: 1

  # backbone parameters
  backbone: stacked_hourglass
  depth: 4
  num_stacks: 2
  num_blocks: 1

  # sampler parameters
  ## static sampler
  n_stc_posl0: 200
  n_stc_posl1: 200
  n_stc_posl2: 200
  n_stc_negl: 200

  ## dynamic sampler
  n_dyn_junc: 600
  n_dyn_posl0: 2000
  n_dyn_posl1: 2000
  n_dyn_posl2: 2000
  n_dyn_negl: 2000
  n_dyn_othr: 2000

  # LOIPool layer parameters
  n_pts0: 32
  n_pts1: 8

  # line verification network parameters
  dim_loi: 256
  dim_fc: 1024

  # maximum junction and line outputs
  n_out_junc: 600
  n_out_line: 2500

  # additional ablation study parameters
  use_cood: 1
  use_slop: 1
  use_conv: 0
  use_wandb: 0
  use_half: 0
  use_jtyp: 1

  # junction threashold for evaluation (See #5)
  eval_junc_thres: 0.1

optim:
  name: Adam
  lr: 4.0e-4
  amsgrad: True
  weight_decay: 0
  max_epoch: 100000
  lr_decay_epoch: 10
