io:
  logdir: /content/drive/MyDrive/smartMTO-Xavier/Train_lcnn_dpid/logs/overfit
  datadir: /content/drive/MyDrive/smartMTO-Xavier/Train_lcnn_dpid/overfit
  resume_from:  #/content/drive/MyDrive/smartMTO-Xavier/Train_lcnn_dpid/logs/twolines/231009-091908-4fbdb8a-baseline
  num_workers: 2
  tensorboard_port: 0
  validation_interval: 24000

model:
  image:
      mean: [247.55]
      stddev: [41.36]

  batch_size: 2
  batch_size_eval: 2

  # backbone multi-task parameters
  # jmap, lmap, joff
  head_size: [[4], [4], [4]]
  loss_weight:
    jmap: 8.0
    lmap: 0.5
    joff: 0.25
    lpos0: 1
    lpos1: 1
    lneg: 1

  # backbone parameters
  backbone: stacked_hourglass
  depth: 4
  num_stacks: 2
  num_blocks: 1

  # sampler parameters
  ## static sampler
  n_stc_posl: 300
  n_stc_negl: 40

  ## dynamic sampler
  n_dyn_junc: 600
  n_dyn_posl1: 300
  n_dyn_posl0: 300
  n_dyn_negl: 80
  n_dyn_othr: 600

  # LOIPool layer parameters
  n_pts0: 64
  n_pts1: 16

  # line verification network parameters
  dim_loi: 256
  dim_fc: 2048

  # maximum junction and line outputs
  n_out_junc: 250
  n_out_line: 2500

  # additional ablation study parameters
  use_cood: 0
  use_slop: 0
  use_conv: 0
  use_lmap: 0

  # junction threashold for evaluation (See #5)
  eval_junc_thres: 0.2

optim:
  name: Adam
  lr: 4.0e-4
  amsgrad: True
  weight_decay: 1.0e-4
  max_epoch: 24
  lr_decay_epoch: 10
